### ISSUE TITLE
scale in cv2.readNet

### ISSUE THREAD

**Issue by Kivin1** [arunponnusamy/object-detection-opencv#5]
Hi,

i am confused about the scale parameter setting to 0.00392 in cv2.readNet.  How to get this figure?  Could you please explain.

thanks a lot

**Comment by arunponnusamy** [comment]
Hi @Kivin1 , I wonder how I missed this to explain in the [blog](https://www.arunponnusamy.com/yolo-object-detection-opencv-python.html) post.
Every neural network architecture has some sort of preprocessing step where images would be normalized (converting the pixel values to range from 0 to 1, instead of 0 to 255) or mean pixel values would be subtracted and so on.

So in YOLO v3, the images are normalized (converting pixel values to range from 0 to 1) before passing through the network. So this scale value 0.00392 is nothing but 1/255. Dividing each pixel value by 255 (which is  equivalent to multiplying with 0.00392) brings them to the range of 0 to 1. 

These steps are decided by the authors of the network. Different research papers propose different preprocessing steps which they find working well. So this scaling is essentially a preprocessing step. Hope this is clear now. Thanks for asking.
